blank_issues_enabled: true
contact_links:
  - name: ✨ Question Answer / Idea
    url: https://github.com/simpledong81/designable/discussions/new
    about: All questions can be solved here. At the same time you can provide all your ideas here.
